### ISSUE TITLE
SAML: Possible to simplify contents of /run/secrets/saml-secrets?

### ISSUE THREAD

**Issue by derekbelrose** [jhu-idc/idc-isle-buildkit#15]
Currently,  the keys, certs and other data for SAML services are presented to Drupal as a YAML object in a file located at /run/secrets/saml-secrets in the following format:

```
saml-secrets:
  idp:
    baseurl:
    entityid:
  sp:
    baseurl:
    entityid:
```
The situation I am in is the Kubernetes secrets are flat. For example:
```
data:
  idp_baseurl:
  idp_entityid:
  sp_baseurl:
  sp_entityid:
```

It is not possible to do anything close to complex YAML. I can take the content of the file itself and run it through base64:
` cat sam-secrets.yaml | base64 -w 0` and then paste the resulting blob as a value to a key under data. That leads to a more difficult management of a file as developers or operations would need to have an extra step of encoding the file instead of changing a simple secret.

I have tried using ConfigMaps which can take arbitrary YAML structure but they cannot reference secrets. Common security practices recommend secret data to be held in Secrets because they can be encrypted, ConfigMaps cannot.

Would it be possible to simplify the structure of the `saml-secrets` file? That way I can continue to pass a file but take advantage of the Secret resource provided by Kubernetes. I'll note that I can work around this problem by encoding the entire file contents with bas64 and then using that as the value, but it's not as manageable and it would be a difference between the developers Docker environment and the Kubernetes deployment environments.

Another option is to use the existing confd setup and use ENV variables but I think Docker lacks the ability to pass Secrets over environment variables. It appears you are just using the structure of the saml-secrets file to create confd structure. Could the same goal be achieved using a more flat YAML structure in the file?

I can create a PR as an example of this if you wish. I have a branch that can be cleaned up with a few hours work.

**Comment by derekbelrose** [comment]
The existing workaround results in a file like this:

```
apiVersion: v1
data:
  saml-secrets: c2FtbC1zZWNyZXRzOgogIHNwOgogICAgYmFzZXVybDogImh0dHBzOi8vdGVzdC5ib2IubGlicmFyeS5qaHUuZWR1IgogICAgZW50aXR5aWQ6ICJodHRwczovL3Rlc3QuYm9iLmxpYnJhcnkuamh1LmVkdS9zaGliYm9sZXRoIgogICAgYWRtaW4tcHc6IG1vbwogICAgaGFzaGluZy1zYWx0OiAxeTNseDY5eDlzZTBhemJnMTN5ZXIxazJxdmE2bjQ4MGVhaDNpdnd3eDIyejFqa2pxbGZib2hjd284eW4yaGFvdXpyYjVyNWhxbG80dGZnZzRvY2Ryd2hqeG00Y200ZW81amh3d3prczQ0bTJhOWJpZDFzcDF6ZXRheXI2bGFiNjFtMWw3N25wODY3NmVzYXRndTFpcHAxYWM4b2dneW5ucm41b3NhemsxZWwzZnlrZWNqcTllMHBnZXNpdDdkdXE5ZTV2cDB2d2cwZzd0ejFyMWE4M3c2cWZlZWpnYWNyczVuOXBzdXA2bXE4djRvdGR3OGphZ29tY2xlbWU1dzVjCiAgICBzaWduaW5nLWNlcnQ6IHwtCiAgICAgIC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQogICAgICBNSUlDNnpDQ0FkT2dBd0lCQWdJSkFPeTBua2kzV0FPVk1BMEdDU3FHU0liM0RRRUJCUVVBTUJjeEZUQVRCZ05WCiAgICAgIEJBTVRERGM1T1RRelptVmxOemcyTlRBZUZ3MHhOVEV5TVRFd016QXdOREphRncweU5URXlNRGdKICAgICAgQUFIc1ZRQ21BSy85a21SaHNXelIzZjFLSXc5OHE0RVg3bkgvSzY4QkZyZXJVdmFMNStmRUdFOVc2S2k2UWRXOAogICAgICBiTTE3R1FrTHlSREtaekdQbSDVnoxYmw5bENWY2VvSjkKICAgICAgRmFMMzhrblMwcDVEblhjbStJOHdxTkVWR0xEUGJEYWxCUXJ5aEpUOWZJTW0xL0I4NWdCM0FXQXZjdTlQUGZISwogICAgICBsUVFVaHh5RVhUQkp4M2x1TGxwSWpvbG9GS0l1dGU5SzdwRTVxQUVUnJpTjR6ZTEreWdkVlZFQTZWRXNINERxcmE2TGc2RlVTcTdHbUdVNTVUVmZDbTJkRmtNK2JPCiAgICAgIEZNT2dzU2tRZlVXZVlrREQ5WDdzWFBBZWhram05OGV2VEltT25OWTVZRlFIT3ExZU14bjZXbjJuTVRpelBLbkcKICAgICAgSVdQTHQwNGtuZEIvcUloaEtvdFpoU3l2TXFlaFNzMS9EbEpFSDFudVBXQjgrc0FjUlRudnY2ZnU4NHNwdGF3YgogICAgICBQNVJuM3B4S1BNNGdpREpvNTZLTnVlMzg5TkczTS9heFpkYTA4U2l4WDRNdTlzVTVSdTlwZXJ2cVFmVmFpdDJECiAgICAgIFNVdWRqYk9WQWdNQkFBRUNnZ0VCQUswcHlzVExzWllsbU1TSGFyMlhianJzTGVjblZUQTU4b2p5K0hIUk8ybmoKICAgICAgbWdNcys3Q1lBdkhsVWNieUpMd1F6UUV6Nzg3cWdXQURvd2I4RTVnWEFTQlVaTEpHeGk3MzhhZEhsVmY5UU43dwogICAgICBrL1MvUkczZmMrRllMYTh1VVRWNmhmR252MDBzVlo5ZXREL2dGdGhNOGM4VnJxUTE2RWdkeldncTI1RzhNS3gxCiAgICAgIGRSSFQ3ZlJsZWhpd251Q3ZVYzlkS0VrZXVuYUJmRHAyUUcrakkwYUtyamVQK04vMHpTeU1EaXlTQ3IveUl3V24KICAgICAgR21tWWREak5LWHVsbFpUSFB4bVRURVg1Z3JhUHRYZURNM2h6NUE9CiAgICAgIC0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  name: saml2
```

I've change the value so that it can't be decoded. In order to make changes, I would need to copy that value, run it through `bas64 -d` redirecting the output to a file. After editing the file I would need to run it through base64 to re-encode it.
